---
driver:
  name: vagrant
  customize:
    memory: 512
    cpuexecutioncap: 50

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: fedora-18
  - name: fedora-19
  - name: fedora-20

suites:
  - name: install
    run_list:
      - recipe[yumgroup::_kitchen_install]
    attributes:
  - name: upgrade
    run_list:
      - recipe[yumgroup::_kitchen_upgrade]
    attributes:
  - name: remove
    run_list:
      - recipe[yumgroup::_kitchen_remove]
    attributes:
