---
driver:
  name: vagrant
  customize:
    memory: 512
    cpuexecutioncap: 50

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: fedora-18
  - name: fedora-19
  - name: fedroa-20

suites:
  - name: default
    run_list:
      - recipe[yumgroup::default]
    attributes:
